name: Gfortran CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    
    - name: gfortran
      run: sudo apt install gfortran
      
    - name: make
      working-directory: ./src
      run: make
