name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: run mps_genesim
      run: ./mps_genesim.exe mps_genesim.txt
      run: ./mps_snesim_tree.exe mps_snesim.txt
      run: ./mps_snesim_list.exe mps_snesim.txt
      
